In [6]:
# Configure Jupyter to display the assigned value after an assignment
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

# Prerequisite Material

Following the notation of <em>Spacecraft Dynamics and Control: An Introduction</em>, First Edition. A.H.J. de Ruiter, C.J. Damaren and J.R. Forbes.  2013 John Wiley & Sons, Ltd.

## Vectors
A vector is a three-dimensional quantity, denoted $ \vec{r} $, with <em>magnitude</em> ($|\vec{r}|$) and <em>direction</em> that satisfies the following rules:

### Addition

\begin{gather}
(\vec{a} + \vec{b}) + \vec{c} = \vec{a} + (\vec{b} + \vec{c}) & \text{associative}\\
\vec{a} + \vec{b} = \vec{b} + \vec{a} & \text{commutative}\\
\vec{a} + \vec{0} = \vec{a} & \text{identity}\\
\vec{a} + (-\vec{a)} = \vec{0} & \text{inverse}
\end{gather}

### Scalar Multiplication

\begin{gather}
a(b\vec{c}) = (ab)\vec{c} \\
(a+b)\vec{c} = a\vec{c} + b\vec{c} \\
a(\vec{b} + \vec{c}) = a\vec{b} + a\vec{c} \\
1\vec{a} = \vec{a} \\
0\vec{a} = \vec{0} 
\end{gather}

### Scalar (Dot) Product

Defined as
\begin{equation}
\vec{a} \cdot \vec{b} \triangleq |\vec{a}| |\vec{b}| \cos \theta
\end{equation}


The dot product is the the projection of $ \vec{a} $ onto $ \vec{b} $ multiplied by $ |\vec{b}| $.

The dot product is commutative $ \vec{a} \cdot \vec{b} = \vec{b} \cdot \vec{a} $.

The dot product is also distributive $ (\vec{a} + \vec{b}) \cdot \vec{c} = \vec{a} \cdot \vec{c} + \vec{b} \cdot \vec{c} $

Additional properties:
\begin{gather}
\vec{a} \cdot \vec{a} = |\vec{a}|^2 \geq 0 \\
\vec{a} \cdot \vec{a} = 0 \Leftrightarrow \vec{a} = \vec{0} \\
\vec{a} \cdot (c\vec{b}) = c\vec{a} \cdot \vec{b} \\
\vec{a} \cdot \vec{b} = 0 \Leftrightarrow \vec{a} \perp \vec{b} \text{ or } \vec{a} = \vec{0} \text{ or } \vec{b} = \vec{0}
\end{gather}

### Vector Cross Product

Defined as 
\begin{equation}
\vec{c} = \vec{a} \times \vec{b}
\end{equation}
where 
\begin{equation}
|\vec{c}| = |\vec{a}| |\vec{b}| \sin \theta
\end{equation}
with the direction perpendicular to $\vec{a}$ and $\vec{b}$ according to the right-hand rule.

Changing the order reverses the direction of the cross-product
\begin{equation}
\vec{a} \times \vec{b} = -\vec{b} \times \vec{a}
\end{equation}

Additional properties:
\begin{gather}
(\vec{a} + \vec{b}) \times \vec{c} = \vec{a} \times \vec{c} + \vec{b} \times \vec{c} & \text{distributive}\\
\vec{a} \times \vec{a} = \vec{0} \\
(a\vec{b}) \times \vec{c} = a(\vec{b} \times \vec{c}) \\
\end{gather}


## Modeling

We will use computer simulation and modeling as the paradigm for learning the material in this course.  We will develop a simulation of orbit trajectories using the [Anaconda distribution](https://www.anaconda.com/) of the [Python programming language](https://www.python.org/).  Our work will be structured like [Allen Downey](https://www.allendowney.com/)'s work in his book [Modeling and Simulation in Python](https://allendowney.github.io/ModSimPy/).  Professor Downey's code and notebooks can be found in his [ModSimPy GitHub repository](https://github.com/AllenDowney/ModSimPy).  Many of the functions used here are from Allen Downey's ModSimPy library.

We will start by creating some functions for vector and matrix operations.

First, create a vector using the pandas Series data structure.  pandas is the [Python Data Analysis Library](https://pandas.pydata.org/).  We will use many pandas data objects in this course.


In [7]:
import pandas as pd

In [8]:
# Define a Vector using the pandas data structure
def Vector(x, y, z=None):
    """
    create a Vector, 2D or 3D
    """
    if z is None:
        return pd.Series(dict(x=x, y=y))
    else:
        return pd.Series(dict(x=x, y=y, z=z))


In [9]:
a = Vector(1,2,3)

x    1
y    2
z    3
dtype: int64

[NumPy](https://numpy.org/) is the Python package for operating on multi-dimensional numerical arrays.  It contains many functions that will allow us to work with vectors and matricies.

In [12]:
import numpy as np

In [13]:
# Define a function to compute the magnitude of a vector
def vector_mag(v):
    """
    magnitude of a vector
    """
    return np.sqrt(np.dot(v,v))

In [14]:
vector_mag(a)

3.7416573867739413

In [15]:
# Define a function to compute the dot product of two vectors
def vector_dot(v, w):
    """
    dot product of v and w
    """
    return np.dot(v, w)

In [16]:
b = Vector(4,5,6)

vector_dot(a,b)

32

In [17]:
# Define a function to compute a unit vector in the direction of v
def vector_hat(v):
    """
    unit vector in the direction of v
    """
    # check if the magnitude of the Quantity is 0
    mag = vector_mag(v)
    if mag == 0:
        return v
    else:
        return v / mag


In [18]:
a_hat = vector_hat(a)

x    0.267261
y    0.534522
z    0.801784
dtype: float64

Check the magnitude of $\vec{a}$, i.e. $|\vec{a}|$

In [19]:
vector_mag(a_hat)

1.0

In [20]:
# Define a function to compute the cross product of two vectors
def vector_cross(v, w):
    """
    cross product of v and w

    returns: number or Quantity for 2-D, Vector for 3-D
    """
    result = np.cross(v, w)

    if len(v) == 3:
        return Vector(*result)
    else:
        return result


In [21]:
c = vector_cross(a, b)


x   -3
y    6
z   -3
dtype: int64

In [22]:
x = np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [23]:
x[0,0]

1

In [24]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [25]:
np.matmul(b, a)

array([[4, 1],
       [2, 2]])

In [26]:
b @ a

array([[4, 1],
       [2, 2]])

In [27]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])