In [2]:
# Configure Jupyter so figures appear in the notebook
%matplotlib inline

# Configure Jupyter to display the assigned value after an assignment
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

In [3]:
# import modsim and install if necessary
try:
    from modsim import *
except ImportError:
    print("Download modsim from the course repository at https://github.com/jeffwalton/AE470")

# Classical Orbital Elements


## Exercises

### 1.  Curtis, Example 4.7, page 211
For a given earth orbit, the elements are $ h = 80,000 km^2/s $, $ e = 1.4 $, $ i = 30^{\circ} $, $ \Omega = 40^{\circ} $, $ \omega = 60^{\circ} $, $ \theta = 30^{\circ} $.

Find the state vectors $ \vec{\mathbf{r}} $ and $ \vec{\mathbf{r}} $ in the geocentric equatorial frame.



In [4]:
import numpy as np

In [5]:
h = 80_000 # km^2/s
ecc = 1.4

inc = np.deg2rad(30.0)
O = np.deg2rad(40.0)
w = np.deg2rad(60.0)
theta = np.deg2rad(30.0)


0.5235987755982988

In [6]:
def C1(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.matrix([[ 1, 0, 0],
            [0, c, s],
            [0, -s, c]])

def C2(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.matrix([[ c, 0, -s],
            [0, 1, 0],
            [s, 0, c]])

def C3(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.matrix([[ c, s, 0],
            [-s, c, 0],
            [0, 0, 1]])

In [28]:
C3(w)

matrix([[ 0.5      ,  0.8660254,  0.       ],
        [-0.8660254,  0.5      ,  0.       ],
        [ 0.       ,  0.       ,  1.       ]])

In [20]:
 C3(O) @ C1(inc) @ C3(w)

matrix([[-0.09906849,  0.89592714,  0.4330127 ],
        [-0.94174915, -0.22496343,  0.25      ],
        [ 0.3213938 , -0.38302222,  0.8660254 ]])

In [24]:
r_vec = Vector(6285.0, 3628.6, 0)

x    6285.0
y    3628.6
z       0.0
Name: component, dtype: float64

In [30]:
(C3()) @ C1(inc) @ C3(w)) @ r_vec

array([-4039.8763903 ,  4814.59977272,  3628.63483139])