In [2]:
# Configure Jupyter so figures appear in the notebook
%matplotlib inline

# Configure Jupyter to display the assigned value after an assignment
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

In [3]:
# import modsim and install if necessary
try:
    from modsim import *
except ImportError:
    print("Download modsim from the course repository at https://github.com/jeffwalton/AE470")

# Classical Orbital Elements


## Exercises

### 1.  Curtis, Example 4.7, page 211
For a given earth orbit, the elements are $ h = 80,000 km^2/s $, $ e = 1.4 $, $ i = 30^{\circ} $, $ \Omega = 40^{\circ} $, $ \omega = 60^{\circ} $, $ \theta = 30^{\circ} $.

Find the state vectors $ \vec{\mathbf{r}} $ and $ \vec{\mathbf{v}} $ in the geocentric equatorial frame.



In [4]:
import numpy as np

In [7]:
mu = 3.986000e+5 # km^3/s^2


398600.0

In [5]:
h = 80_000 # km^2/s
ecc = 1.4

inc = np.deg2rad(30.0)
O = np.deg2rad(40.0)
w = np.deg2rad(60.0)
theta = np.deg2rad(30.0)


0.5235987755982988

In [23]:
r = ((h**2)/mu)/(1 + ecc*np.cos(theta))

7491.824158513841

In [24]:
rp_vec = Vector(r*np.cos(theta),r*np.sin(theta),0)

x    6488.110042
y    3745.912079
z       0.000000
Name: component, dtype: float64

In [25]:
vp_vec = Vector(-mu/h*np.sin(theta),mu/h*(ecc+np.cos(theta)),0)

x   -2.847143
y    9.145168
z    0.000000
Name: component, dtype: float64

In [26]:
def C1(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.matrix([[ 1, 0, 0],
            [0, c, s],
            [0, -s, c]])

def C2(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.matrix([[ c, 0, -s],
            [0, 1, 0],
            [s, 0, c]])

def C3(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.matrix([[ c, s, 0],
            [-s, c, 0],
            [0, 0, 1]])

In [27]:
rot_mat_peri_to_geoinertial = C3(O) @ C1(inc) @ C3(w)

matrix([[ 2.87813994e-01, -7.66044443e-01,  5.74751265e-01],
        [ 3.43003361e-01,  6.42787610e-01,  6.84961884e-01],
        [-8.94154237e-01,  1.64253469e-16,  4.47759088e-01]])

In [28]:
r_vec = rot_mat_peri_to_geoinertial @ rp_vec

array([-1002.16626942,  4633.26942307, -5801.3710831 ])

In [29]:
v_vec = rot_mat_peri_to_geoinertial @ vp_vec

array([-7.82505231,  4.9018208 ,  2.54578485])

 ## Problem from Slides

In [30]:
h = 70_000 # km^2/s
ecc = 0.74

inc = np.deg2rad(63.4)
O = np.deg2rad(40.0)
w = np.deg2rad(270.0)
theta = np.deg2rad(30.0)

0.5235987755982988

In [31]:
r = ((h**2)/mu)/(1 + ecc*np.cos(theta))

7491.824158513841

In [32]:
rp_vec = Vector(r*np.cos(theta),r*np.sin(theta),0)

x    6488.110042
y    3745.912079
z       0.000000
Name: component, dtype: float64

In [33]:
vp_vec = Vector(-mu/h*np.sin(theta),mu/h*(ecc+np.cos(theta)),0)

x   -2.847143
y    9.145168
z    0.000000
Name: component, dtype: float64

In [34]:
rot_mat_peri_to_geoinertial = C3(O) @ C1(inc) @ C3(w)

matrix([[ 2.87813994e-01, -7.66044443e-01,  5.74751265e-01],
        [ 3.43003361e-01,  6.42787610e-01,  6.84961884e-01],
        [-8.94154237e-01,  1.64253469e-16,  4.47759088e-01]])

In [35]:
r_vec = rot_mat_peri_to_geoinertial @ rp_vec

array([-1002.16626942,  4633.26942307, -5801.3710831 ])

In [36]:
v_vec = rot_mat_peri_to_geoinertial @ vp_vec

array([-7.82505231,  4.9018208 ,  2.54578485])